import type { GetStaticProps } from 'next';
import Head from 'next/head';

import About from '../components/About';
import Contact from '../components/Contact';
import Hero from '../components/Hero';
import Projects from '../components/Projects';
import WorkExperience from '../components/WorkExperience';
import { PageInfo } from '../typings';
import { fetchPageInfo } from '../utils/fetchPageInfo';

interface Props {
  pageInfo: PageInfo,
}

const Home = ({ pageInfo }: Props) => {

  return (
    <>
      <Head>
        <title>{`<DaianScuarissi />`}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <section id='hero' className='snap-start'>
        <Hero />
      </section>

      <section id='about' className='snap-start'>
        <About />
      </section>

      <section id='experience' className='snap-center'>
        <WorkExperience />
      </section>

      {/* <section id='skills' className='snap-center'>
        <Skills />
      </section> */}

      <section id='projects' className='snap-center'>
        <Projects />
      </section>

      <section id='contact' className='snap-center'>
        <Contact pageInfo={pageInfo} />
      </section>
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps<Props> = async () => {
  const pageInfo: PageInfo = await fetchPageInfo();
  return {
    props: {
      pageInfo,
    },
  };
};
